name: CI

on:
  push:
    branches:
      - '[0-9]+.[0-9]+'
      - master
  pull_request: ~

jobs:
  tests:
    name: Tests
    runs-on: "ubuntu-20.04"
    timeout-minutes: 5
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        php:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
        composer_options: [ "" ]
        include:
          - php: '8.0'
            composer_options: "--ignore-platform-req php"
            experimental: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: pdo_sqlite, gd
          tools: cs2pr

      - uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "highest"
          composer-options: "--prefer-dist --no-progress --no-suggest ${{ matrix.composer_options }}"

      - name: Run PHPStan analysis
        run: composer run-script phpstan

      - name: Run code style check
        run: composer run-script check-cs -- --format=checkstyle | cs2pr
